import type { Metadata } from "next";
import { ThemeProvider } from "../providers/ThemeProvider";
import "../styles/globals.css";
import { Toaster } from "sonner";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body>
        
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex min-h-screen w-full flex-col">
            <Header/>
            </div>
           <main className="flex flex-1 flex-col px-4 pt-10 xl:px-8">{children}</main> 
            <Toaster/>
          </ThemeProvider>
      </body>
    </html>
  );
}
